OBJS = fileutil-29808146.c
CC = gcc
CFLAGS = -Wall -c
LFLAGS = -Wall

fileutil: $(OBJS)
	$(CC) $(LFLAGS) $(OBJS) -o fileutil

# main.o: main.c arithmetic.h
# 	$(CC) $(CFLAGS) main.c -o main.o

# arithmetic.o: arithmetic.c arithmetic.h
# 	$(CC) $(CFLAGS) arithmetic.c -o arithmetic.o